services:
  myapi:
    image: myapi-image  # Nombre de la imagen que construiste
    #image: edygc1988/tes_car_2023:myapi-image  # Nombre de la imagen que construiste
    ports:
      - '8080:8080'  # Puerto de tu aplicación    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/integra?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    depends_on:
       - mysql
  mysql:
    image: 'mysql:latest'
    #image: 'edygc1988/tes_car_2023:mysql'
    environment:
      - 'MYSQL_DATABASE=integra'
      - 'MYSQL_PASSWORD=integra'
      - 'MYSQL_ROOT_PASSWORD=integra'
      - 'MYSQL_USER=integra'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: 'nginx:latest'
    #image: 'edygc1988/tes_car_2023:testing'
    ports:
      - '81:80'
    depends_on:
      - myapi
    volumes:
      - ./nginx-config:/etc/nginx/conf.d # Aquí debes proporcionar la configuración de Nginx

volumes:
  db_data: {}

